/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./src/components/Chart.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    DataSidebar: typeof import('./src/components/DataSidebar.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JobCategory: typeof import('./src/components/JobCategory.vue')['default']
    Knowledge: typeof import('./src/components/Knowledge.vue')['default']
    MaskLayer: typeof import('./src/components/MaskLayer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Statement: typeof import('./src/components/Statement.vue')['default']
  }
}
