/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AICode: typeof import('./src/components/AICode.vue')['default']
    AirLineContainer: typeof import('./src/components/charts/airLineContainer.vue')['default']
    BarContainer: typeof import('./src/components/charts/BarContainer.vue')['default']
    Chart: typeof import('./src/components/Chart.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    DataSidebar: typeof import('./src/components/DataSidebar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HorizontalBarContainer: typeof import('./src/components/charts/HorizontalBarContainer.vue')['default']
    JobCategory: typeof import('./src/components/JobCategory.vue')['default']
    Knowledge: typeof import('./src/components/Knowledge.vue')['default']
    LineContainer: typeof import('./src/components/charts/LineContainer.vue')['default']
    MaskLayer: typeof import('./src/components/MaskLayer.vue')['default']
    NumberQuestion: typeof import('./src/components/NumberQuestion.vue')['default']
    PieContainer: typeof import('./src/components/charts/PieContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Statement: typeof import('./src/components/Statement.vue')['default']
  }
}
